//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CaveEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAVEEDITOR_DIALOG           102
#define DIALOG_CAVEEDITOR_DIALOG        102
#define IDR_MAINFRAME                   128
#define MENU_MAIN                       129
#define MENU_LIST                       131
#define DIALOG_MAP_EDIT                 132
#define DIALOG_TILE_SELECT              135
#define DIALOG_PALETTE_SELECT           136
#define DIALOG_SCRIPT_EDITOR            137
#define DIALOG_PBM_EDITOR               138
#define MENU_PBM                        139
#define DIALOG_DISPLAY_VIEW             140
#define DIALOG_MAP_PROPERITES           141
#define DIALOG_MAP_INFO                 142
#define ICON_WATER                      143
#define DIALOG_ENTITY_INFO              143
#define ICON_SOLID                      144
#define DIALOG_FLAG_DETAIL              144
#define ICON_SEEN                       145
#define MENU_MAP_EDIT_CONTEXT           145
#define ICON_HIDDEN                     146
#define IDC_CURSOR1                     146
#define CURSOR_NULL                     146
#define CURSOR_PIXEL                    146
#define MENU_PBM1                       146
#define MENU_TILESET                    146
#define COMBO_HURT_SOUND                146
#define DIALOG_GAME_SETTINGS            147
#define COMBO_DEATH_SOUND               147
#define MENU_MAP_EDIT_CONTEXT1          147
#define MENU_MAP_EDIT                   147
#define CURSOR_FILL                     147
#define DIALOG_TILESET_EDITOR           148
#define COMBO_DEATH_GRAPHIC             148
#define CURSOR_RECT                     148
#define IDR_MENU1                       149
#define CURSOR_REPLACE                  149
#define DIALOG_RESIZE                   150
#define DIALOG_PALETTE_EDITOR           151
#define DIALOG_NPC_TABLE_EDITOR         152
#define DIALOG_OPTIONS                  153
#define DIALOG_TEXT                     154
#define DIALOG_WEAPON_EDITOR            155
#define DIALOG_NPC_EXE_EDITOR           156
#define DIALOG_MAP_REORDER              158
#define BUTTON_SCRIPT_EDIT              1003
#define BUTTON_NPCTABLE_EDIT            1004
#define BUTTON_EDIT_PBM                 1005
#define BUTTON_GAME_SETTINGS            1011
#define LIST_MAPS                       1012
#define LIST_TILESETS                   1013
#define LIST_SCRIPTS                    1014
#define BUTTON_TILESET_EDIT             1015
#define BUTTON_MAP_EDIT                 1016
#define BUTTON_MAP_DELETE               1017
#define BUTTON_MAP_ADD                  1018
#define BUTTON_TILESET_ADD              1019
#define BUTTON_TILESET_DELETE           1020
#define BUTTON_TILESET_COPY             1021
#define BUTTON_MAP_COPY                 1022
#define LIST_SPRITES                    1023
#define BUTTON_SPRITES_ADD              1024
#define BUTTON_SPRITES_EDIT             1025
#define BUTTON_SPRITES_COPY             1026
#define BUTTON_SPRITES_DELETE           1027
#define LIST_BACKGROUNDS                1028
#define BUTTON_BACKGROUND_ADD           1029
#define BUTTON_BACKGROUND_EDIT          1030
#define BUTTON_BACKGROUND_COPY          1031
#define BUTTON_BACKGROUND_DELETE        1032
#define STATIC_MAPS                     1033
#define STATIC_TILESET                  1034
#define STATIC_TILESETS                 1034
#define STATIC_SPRITES                  1035
#define STATIC_BACKGROUNDS              1036
#define STATIC_SCRIPTS                  1037
#define FRAME_MAP                       1040
#define BUTTON_PROPERTIES               1042
#define TEXT_COORDS                     1043
#define TEXT_COORDS2                    1044
#define TEXT_REDRAW                     1044
#define SCROLLBAR_HORZ                  1047
#define SCROLLBAR_VERT                  1048
#define CHECK_FRONT_TILES               1051
#define CHECK_BACK_TILES                1052
#define CHECK_BACKGROUND                1053
#define CHECK_ENTITIES                  1054
#define CHECK_ENTITY_SPRITES            1055
#define RADIO_ENTITY                    1056
#define RADIO_MAP                       1057
#define BUTTON_SYNTAX                   1057
#define CHECK_ENTITY_TEXT               1058
#define BUTTON_SAVE                     1059
#define BUTTON_DETAILS                  1061
#define TEXT_COMMAND                    1062
#define TEXT_SYNTAX                     1063
#define TEXT_DESC                       1064
#define LIST_COMMANDS                   1065
#define TEXT_EXTRAS                     1066
#define EDIT_SCRIPT                     1067
#define RECT_DISPLAY                    1069
#define EDIT_MAP_NAME                   1070
#define EDIT_MAP_CAPTION                1071
#define COMBO_MAP_TILESET               1072
#define COMBO_MAP_BACKGROUND_SCROLL     1073
#define COMBO_MAP_BACKGROUND            1074
#define COMBO_MAP_NPC_TILESET1          1075
#define COMBO_MAP_NPC_TILESET2          1076
#define COMBO_BOSS_ID                   1077
#define EDIT_MAP_SIZEX                  1078
#define EDIT_MAP_SIZEY                  1079
#define FRAME_SCRIPT_SMALL              1081
#define FRAME_SCRIPT_LARGE              1082
#define CHECK_TILE_GRID                 1082
#define FRAME_SCRIPT_HELP               1082
#define CHECK_TILE_TYPES                1083
#define BUTTON_MAP_SCRIPT               1086
#define FRAME_INFO                      1089
#define RADIO_DRAW_TILES                1090
#define RADIO_FILL_TILES                1091
#define RADIO_BLOCK_TILES               1092
#define RADIO_RECT_TILES                1092
#define RADIO_REPLACE_TILES             1093
#define FRAME_TILE_VIEW                 1094
#define EDIT_ENTITY_ID                  1097
#define EDIT_EVENT_ID                   1098
#define EDIT_FLAG_ID                    1099
#define EDIT_FLAGS                      1100
#define BUTTON_FLAG_DETAILS             1101
#define CHECK_FLAG1                     1102
#define CHECK_FLAG2                     1103
#define CHECK_FLAG3                     1104
#define CHECK_FLAG4                     1105
#define CHECK_FLAG5                     1106
#define CHECK_FLAG6                     1107
#define CHECK_FLAG7                     1108
#define CHECK_FLAG8                     1109
#define CHECK_FLAG9                     1110
#define CHECK_FLAG10                    1111
#define CHECK_FLAG11                    1112
#define CHECK_FLAG12                    1113
#define CHECK_FLAG13                    1114
#define CHECK_FLAG14                    1115
#define CHECK_FLAG15                    1116
#define CHECK_FLAG16                    1117
#define TEXT_INFO                       1120
#define FRAME_ENTITY                    1121
#define IDC_BUTTON1                     1122
#define BUTTON_SHOW_TILESET             1122
#define BUTTON_NEXT                     1122
#define BUTTON_PREV                     1123
#define BUTTON_OK                       1124
#define TEXT_INDEX                      1125
#define TEXT_RED                        1126
#define EDIT_START_EVENT                1126
#define TEXT_GREEN                      1127
#define EDIT_WIDTH                      1127
#define EDIT_TITLE_EVENT                1127
#define TEXT_BLUE                       1128
#define EDIT_HEIGHT                     1128
#define EDIT_START_FACING               1128
#define TEXT_HEIGHT                     1129
#define EDIT_START_X                    1129
#define TEXT_WIDTH                      1130
#define EDIT_START_Y                    1130
#define FRAME_TILESET                   1131
#define EDIT_TITLE_X                    1131
#define FRAME_BACKGROUND                1132
#define EDIT_TITLE_Y                    1132
#define EDIT_HP                         1135
#define EDIT_ATTACK                     1136
#define EDIT_XP                         1137
#define COMBO_TILESET                   1141
#define FRAME_NPC                       1144
#define EDIT_HIT_TOP                    1145
#define EDIT_HIT_LEFT                   1146
#define EDIT_HIT_RIGHT                  1147
#define EDIT_HIT_BOTTOM                 1148
#define EDIT_DISPLAY_TOP                1149
#define EDIT_DISPLAY_LEFT               1150
#define EDIT_DISPLAY_RIGHT              1151
#define EDIT_DISPLAY_BOTTOM             1152
#define COMBO_TEST_TILESET              1153
#define BUTTON_CANCEL                   1154
#define EDIT_DESC                       1156
#define EDIT_DESC1                      1157
#define EDIT_DESC2                      1158
#define EDIT_OPTION1                    1159
#define EDIT_OPTION2                    1160
#define CHECK_1                         1161
#define CHECK_2                         1162
#define TEXT_DEBUG                      1162
#define IDC_EDIT1                       1163
#define EDIT_SCALE                      1163
#define EDIT_NAME                       1163
#define EDIT_TEXT                       1163
#define EDIT_PBM_EXT                    1163
#define EDIT_WEP_DAMAGE                 1163
#define EDIT_NPC_CODE                   1163
#define EDIT_SCALE2                     1164
#define EDIT_TILESET_SCALE              1164
#define EDIT_WEP_HITS                   1164
#define EDIT_NPC_CODE_RAW               1164
#define RADIO_WHEEL_ZOOM                1165
#define EDIT_WEP_RANGE                  1165
#define RADIO_WHEEL_SCROLL              1166
#define EDIT_WEP_SHOT_WIDTH             1166
#define CHECK_TILESET_WINDOW            1167
#define EDIT_WEP_SHOT_HEIGHT            1167
#define EDIT_WEP_WALL_HEIGHT            1168
#define TEXT_ALPHA                      1169
#define EDIT_WEP_WALL_WIDTH             1169
#define SLIDER_ALPHA                    1170
#define EDIT_WEP_LEFT_GRPHIC_OFFSET     1170
#define TEXT_ALPHA_TEST_AREA            1171
#define EDIT_WEP_RIGHT_GRPHIC_OFFSET    1171
#define EDIT_WEP_VERT_GRPHIC_OFFSET     1172
#define SLIDER_BLUE                     1173
#define EDIT_WEP_EXP                    1173
#define SLIDER_GREEN                    1174
#define SLIDER_RED                      1175
#define FRAME_COLOR                     1176
#define TEXT_RED2                       1177
#define TEXT_GREEN2                     1178
#define TEXT_BLUE2                      1179
#define FRAME_24BIT                     1180
#define EDIT_TITLE                      1181
#define EDIT_SAVE_FILE_NAME             1182
#define CHECK_NO_C_PIXEL                1183
#define EDIT_C_PIXEL                    1185
#define EDIT_START_HP                   1186
#define EDIT_START_MAX_HP               1187
#define FRAME_WEP_IMAGE                 1190
#define TEXT_WEP_LEVEL                  1191
#define CHECK_FLAG01                    1193
#define CHECK_FLAG02                    1194
#define TEXT_OPCODE_DESC                1194
#define CHECK_FLAG04                    1195
#define CHECK_FLAG08                    1196
#define TEXT_SCRIPT_DESC                1196
#define TEXT_SCRIPT_COMMAND             1197
#define CHECK_FLAG20                    1198
#define TEXT_SCRIPT_FRAME1              1198
#define CHECK_FLAG40                    1199
#define TEXT_SCRIPT_FRAME2              1199
#define CHECK_FLAG80                    1200
#define IDC_LIST2                       1201
#define COMBO_START_MAP                 1202
#define COMBO_TITLE_MAP                 1203
#define IDC_COMBO1                      1203
#define COMBO_ENTITY_TYPE               1203
#define CHECK_READ_ONLY                 1204
#define EDIT_COLORDEPTH                 1206
#define ID_FILE_LOAD                    32772
#define ID_FILE_TEST                    32774
#define ID_HELP_CONTENTS                32775
#define ID_HELP_ABOUT                   32776
#define ID_OPTIONS                      32777
#define ID_EDIT_TILES                   32778
#define ID_EDIT_MAP                     32779
#define ID_EDIT_ENTITYTABLE             32780
#define ID_EDITPROPERTIES               32782
#define ID_COPYMAP                      32783
#define ID_DELETEMAP                    32784
#define ID_EDITMAP                      32786
#define ID_EDITBACKGROUND               32787
#define ID_COPYBACKGROUND               32788
#define ID_DELETEBACKGROUND             32789
#define ID_MAPLIST_                     32790
#define ID_MAPLIST_EDITMAPPROPERTIES    32792
#define ID_MAPLIST_COPYMAP              32793
#define ID_MAPLIST_DELETEMAP            32794
#define ID_BACKGROUNDLIST_EDITBACKGROUND 32795
#define ID_BACKGROUNDLIST_COPYBACKGROUND 32796
#define ID_BACKGROUNDLIST_DELETEBACKGROUND 32797
#define ID_TILESETLIST_EDITTILESET      32798
#define ID_TILESETLIST_COPYTILESET      32799
#define ID_MAPLIST_ADDMAP               32800
#define ID_TILESETLIST_DELETETILESET    32801
#define ID_SPRITESETLIST_EDITSPRITESET  32802
#define ID_SPRITESETLIST_COPYSPRITESET  32803
#define ID_SPRITESETLIST_DELETESPRITESET 32804
#define ID_MAPLIST_EDITMAPSCRIPT        32805
#define ID_SCRIPTLIST                   32806
#define ID_SCRIPTLIST_EDITSCRIPT        32807
#define ID_VIEW_32X32GRID               32812
#define ID_MAPLIST_EDITMAP              32814
#define ID_ENTITY_ADDENTITY             32815
#define ID_ENTITY_DELETEENTITY          32816
#define ID_ENTITY_COPYENTITY            32817
#define ID_ENTITY_PASTEENTITY           32818
#define ID_VIEW_64X64GRID               32820
#define ID_VIEW_16X16GRID               32821
#define ID_VIEW_GRIDOFF                 32822
#define ID_BASE_0                       32823
#define ID_BASE_1                       32824
#define ID_BASE_2                       32825
#define ID_BASE_3                       32826
#define ID_BASE_4                       32827
#define ID_BASE_5                       32828
#define ID_BASE_6                       32829
#define ID_BASE_7                       32830
#define ID_BASE_8                       32831
#define ID_BASE_9                       32832
#define ID_BASE_10                      32833
#define ID_BASE_16                      32834
#define ID_BASE_32                      32835
#define ID_BASE_48                      32836
#define ID_BASE_64                      32837
#define ID_BASE_80                      32838
#define ID_BASE_96                      32839
#define ID_BASE_112                     32840
#define ID_BASE_138                     32841
#define ID_BASE_154                     32842
#define ID_TOOLS_RESIZE                 32845
#define ID_TOOLS_EDITPALETTE            32846
#define ID_FILE_EXIT                    32847
#define ID_MAP_SHIFTMAP                 32848
#define ID_ZOOM_1                       32849
#define ID_ZOOM_1X                      32851
#define ID_ZOOM_2X                      32852
#define ID_ZOOM_3X                      32853
#define ID_ZOOM_4X                      32854
#define ID_ZOOM_05X                     32855
#define ID_MAP_EDITSCRIPT               32856
#define ID_MAP_PROPERTIES               32857
#define ID_MAP_SAVE                     32858
#define ID_COORDS                       32859
#define ID_DATA_EDITBULLETTABLE         32860
#define ID_DATA_WEAPONTABLE             32861
#define ID_DATA_BULLETDATA              32862
#define ID_DATA_WEAPONDATA              32863
#define ID_DATA_NPCEXEDATA              32864
#define ID_DATA_REORDERMAPLIST          32873
#define ID_Menu                         32874
#define ID_MAP_SETSTARTLOCATION         32875
#define ID_ENTITYSELECTED_ID            32876
#define ID_SORTENTITIIESBY_CATEGORY     32882
#define ID_SORTENTITIIESBY_NAME         32883
#define ID_SORTENTITIIESBY_IDNUMBER     32884
#define ID_ENTITIES_DELETEALL           32885

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32886
#define _APS_NEXT_CONTROL_VALUE         1207
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
